### ISSUE TITLE
Undefined behaviour when too many arguments are added

### ISSUE THREAD

**Issue by Hazurl** [MayaPosch/Sarge#1]
In the function [`Sarge::setArgument`](https://github.com/MayaPosch/Sarge/blob/master/src/sarge.cpp#L23), the map insert a pointer to
the Argument in the vector, but [`std::vector::push_back`](https://en.cppreference.com/w/cpp/container/vector/push_back) invalidate all reference if you exceed the capacity of the vector.

I would suggest to change either :
- `std::vector<std::unique_ptr<Argument>> args`, and use `args.back().get()`
- `std::map<std::string, std::size_t> argNames`, to only keep the index of the argument
- `std::map<std::string, std::shared_ptr<Argument>> argNames` and get rid of `Sarge::args` and use

**Comment by MayaPosch** [comment]
Fix has been implemented and pushed. Please verify.

**Comment by Hazurl** [comment]
All good 👌

**Comment by MayaPosch** [comment]
Thank you :)
