### ISSUE TITLE
Doesn't accept negative integer value in option

### ISSUE THREAD

**Issue by anttijuu** [MayaPosch/Sarge#2]
Had a case where negative value could have been accepted in the option value. Since it starts with "-", it is considered to be an option / flag itself and this does not succeed.

Implemented a quick fix, if you want to check if that is OK and add support for negative integer values in options. Diff below. Please note that I have not extensively tested this, so it might need fixing.

Thanks for the Sarge, btw, convenient and easy to use.

```
diff --git a/../../Sarge/src/Sarge.cpp b/Sarge.cpp
index f401695..f4129f7 100644
--- a/../../Sarge/src/Sarge.cpp
+++ b/Sarge.cpp
@@ -59,7 +59,12 @@ bool Sarge::parseArguments(int argc, char** argv) {
 		// same string if they're the short form flag type (one character per flag).
 		std::string entry(argv[i]);
 		
-		if (entry.compare(0, 1, "-") == 0) {
+		if (expectValue) {
+			// Copy value.
+			flag_it->second->value = entry;
+			
+			expectValue = false;
+		} else if (entry.compare(0, 1, "-") == 0) {
 			// Parse flag.
 			// First check for the long form.
 			if (entry.compare(0, 2, "--") == 0) {
@@ -98,24 +103,20 @@ bool Sarge::parseArguments(int argc, char** argv) {
 					flag_it->second->parsed = true;
 					++flagCounter;
 					
-					if (i != (entry.length() - 1) && flag_it->second->hasValue) {
-						// Flag isn't at end, thus cannot have value.
-						std::cerr << "Flag " << k << " needs to be followed by a value string." 
-									<< std::endl;
-						return false;
-					}
-					else {
-						expectValue = true; // Next argument has to be a value string.
-					}
+					if (flag_it->second->hasValue) {
+						if (i != entry.length() - 1) {
+							// Flag isn't at end, thus cannot have value.
+							std::cerr << "Flag " << k << " needs to be followed by a value string."
+							<< std::endl;
+							return false;
+						}
+						else {
+							expectValue = true; // Next argument has to be a value string.
+						}
+					}
 				}
 			}
 		}
-		else if (expectValue) {
-			// Copy value.
-			flag_it->second->value = entry;
-			
-			expectValue = false;
-		}
 		else {
 			std::cerr << "Expected flag, not value." << std::endl;
 			return false;
```

**Comment by MayaPosch** [comment]
I have pushed a change to the main branch along with an improved testing app which covers this scenario. Local testing looks okay. Please check that it also works for you now :)

**Comment by anttijuu** [comment]
Thanks, tested but found an issue. See the suggested change in my diff:

```
if (flag_it->second->hasValue) {
+						if (i != entry.length() - 1) {
```
In the (current version) line 107 which is not in current version. I guess lacking this, the command line option

`./GenerateTestData -e 3 -s 1000 -b 10 -v`

works (it shouldn't since last option has no value), but the correctly given one gives an error:

```
$ ./GenerateTestData -v -e 3 -s 1000 -b 10 
Expected flag, not value.
Could not parse arguments
```

**Comment by anttijuu** [comment]
Sorry, should have done a pull request to provide you clearer patch.

**Comment by anttijuu** [comment]
So to clear my patch info, from line 107 it would go like this:

```
	      if (flag_it->second->hasValue) {
                  if (i != (entry.length() - 1)) {
                     // Flag isn't at end, thus cannot have value.
                     std::cerr << "Flag " << k << " needs to be followed by a value string."
                     << std::endl;
                     return false;
                  } else {
                     expectValue = true; // Next argument has to be a value string.
                  }
               }
```

**Comment by anttijuu** [comment]
But then `$ ./GenerateTestData  -ve 3 ` is not working. I'll have to investigate more.

**Comment by anttijuu** [comment]
> But then `$ ./GenerateTestData -ve 3 ` is not working. I'll have to investigate more.

Sorry this was my bad, my app requires option s always, that was the issue. So e.g. `$ ./GenerateTestData -ve 3` **is** working correctly.

**Comment by MayaPosch** [comment]
Thank you, that fixes a subtle bug with multiple short flags being passed :)

Please check that the current state of the code passes all tests for you.

**Comment by anttijuu** [comment]
All seems to be working fine now, both in the Sarge test app and in my test file generator. Thanks!  :)
